# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [12]:
A = np.arange(1, 16).reshape(3,5) 

print(A)
print()

print(A.ndim) #number of axes
print()

print (A.shape)#shape
print()

print (A.itemsize)#size

print (type (A))#datatype


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

2

(3, 5)

4
<class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [181]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [182]:
print (B-C)#Elementwise subtraction

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [16]:
print (B*C)#Elementwise multiplication.

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [26]:
print (B.dot(C)) #Matrix multiplication (B*C)

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


In [25]:
print (C.dot(B)) #Matrix multiplication (C*B)

[[24. 30. 36.]
 [24. 30. 36.]
 [24. 30. 36.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [24]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [336]:
B_exp=np.exp(B) #Exponentiate each number elementwise
print (B_exp)

[[0.36787944 2.71828183]
 [2.71828183 0.36787944]]


In [34]:
print (B.min()) # the minimum value in the whole matrix

1


In [35]:
print (B.min(axis=1))# the minimum value in each row.

[1 4 7]


In [37]:
print (B.min(axis=0)) # the minimum value in each column

[1 2 3]


In [39]:
B_ind_matrix=np.argmin(B) # the index value for the minimum value in the whole matrix
print(B_ind_matrix)

0


In [45]:
B_ind_row=np.argmin(B, axis=1) #The index value for the minimum value in each row
print(B_ind_row)

[0 0 0]


In [47]:
print(B.sum()) #the sum for all elements

45


In [49]:
B_mean=np.mean(B,axis=0) #the mean for each column
print(B_mean)

[4. 5. 6.]


In [53]:
B_median=np.median(B,axis=0)#the median for each column
print(B_median)

[4. 5. 6.]


In [58]:
print(B[1])

[4 5 6]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [60]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [75]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
#The program returns all data which located on the indicated axis

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [77]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [80]:
for i in A.flat: #to iterate through the array elementwise// we can use the flat attribute 
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [90]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
#The code returns the array with a modified shape.  
#The first axis has a length of 2, the second axis has a length of 3. 
#Lengt of the third axis is undefined. "-1" means that the  dimensions for third axis  are calculated automatically.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [91]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [92]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [93]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [199]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [240]:
def add_mult_matrices(Matrix_1, Matrix_2, add_or_multiply):
    
    if not isinstance(Matrix_1, np.ndarray) or not isinstance(Matrix_2, np.ndarray):
        raise ("The matrices must be numpy arrays.")
        
    if add_or_multiply == 'add':
        if Matrix_1.shape != Matrix_2.shape:
            raise ValueError('For addition Matrix_1 and Matrix_2 must have the same shape.')
        else:
            return Matrix_1 + Matrix_2
        
            
    elif add_or_multiply == 'multiply':
        if Matrix_1.shape[1] != Matrix_2.shape[0]:
            raise ValueError('The number of rows in Matrix_1 must be equal to the number of columns in Matrix_2.')
            
        else:
            return (Matrix_1.dot(Matrix_2))
        
    else:
        raise Exception('the add_or_multiply argument must be "add" or "multiply". ')
        


In [223]:
# B - 2A
add_mult_matrices(B, -2*A, 'add') 

array([[ 0, -4,  3],
       [ 0, -2, -4]])

In [224]:
# 3C - E
add_mult_matrices(3*C, -1*E, 'add')

ValueError: For addition Matrix_1 and Matrix_2 must have the same shape.

In [225]:
#AC
add_mult_matrices(A, C, 'multiply')

ValueError: The number of rows in Matrix_1 must be equal to the number of columns in Matrix_2.

In [226]:
#CD
add_mult_matrices(C, D, 'multiply')

array([[11, 10],
       [10, 11]])

In [227]:
#CB
add_mult_matrices(C, B, 'multiply')

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

**Chap2. Question 2**

In [238]:
A=np.array([[1,2], [2,4]])
B=np.array([[2,1],[1,3]])
C=np.array([[4,3], [0,2]])

In [241]:
#AB
AB = add_mult_matrices(A, B, 'multiply')

In [243]:
#AC
AC=add_mult_matrices(A, C, 'multiply')

In [248]:
print ('AB=', add_mult_matrices(A, B, 'multiply'))
print()
print ('AC=', add_mult_matrices(A, C, 'multiply'))
print()
print('AB=AC:', '\n',(AB == AC).all())
print()
print('B=C: ','\n', (B==C).all())

AB= [[ 4  7]
 [ 8 14]]

AC= [[ 4  7]
 [ 8 14]]

AB=AC: 
 True

B=C:  
 False


**Chap2. Question 3**

In [251]:
A=np.array([[1,1,1], [1,2,3],[1,3,4]])
D=np.array([[2,0,0], [0,3,0], [0,0,4]])

In [252]:
#AD

AD=add_mult_matrices(A, D, 'multiply')
print ('A*D=',add_mult_matrices(A, D, 'multiply'))

A*D= [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]


In [253]:
#DA

DA=add_mult_matrices(D, A, 'multiply')
print ('D*A=',add_mult_matrices(D, A, 'multiply'))

D*A= [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


In [254]:
# Compute AD and DA

print('AD=DA:', '\n',(AD == DA).all())

AD=DA: 
 False


**Quiz p.11, Question 2**

In [256]:
A=np.array([[1,-1], [-1,1]])
B=np.array([[-1,1], [1,-1]])

Answer_a=np.array([[-2,2], [2,-2]])
Answer_b=np.array([[2,-2], [-2,2]])
Answer_c=np.array([[-2,2], [-2,2]])
Answer_d=np.array([[-2,-2], [2,2]])

In [259]:
AB=add_mult_matrices(A, B, 'multiply')
print ('A*B=',add_mult_matrices(A, B, 'multiply'))

A*B= [[-2  2]
 [ 2 -2]]


In [260]:
#A*B

AB=add_mult_matrices(A, B, 'multiply')
print ('A*B=',add_mult_matrices(A, B, 'multiply'))

A*B= [[-2  2]
 [ 2 -2]]


In [261]:
#Choosing which matrix (Answer_a,b,c or d) is equal to A*B

print('Answer_a:', '\n',(AB == Answer_a).all())
print ()
print('Answer_b:', '\n',(AB == Answer_b).all())
print ()
print('Answer_c:', '\n',(AB == Answer_c).all())
print ()
print('Answer_d:', '\n',(AB == Answer_d).all())


Answer_a: 
 True

Answer_b: 
 False

Answer_c: 
 False

Answer_d: 
 False


**Chap 6. Question 1**

In [275]:
A_ch6=np.array([[5,6],[4,5]])
B_ch6=np.array([[6,4],[3,3]])

I=np.eye(2)

print(I)

[[1. 0.]
 [0. 1.]]


In [269]:
#Find the inverses of the matrices A_ch6

A_ch6_inv = np.linalg.inv(A_ch6)
print('The inverses of the matrices A_ch6: ', A_ch6_inv)

The inverses of the matrices A_ch6:  [[ 5. -6.]
 [-4.  5.]]


In [272]:
#Verification

print ('A_ch6*A_ch6_inv=I is ', np.allclose(A_ch6.dot(A_ch6_inv), I))


A_ch6*A_ch6_inv=I is  True


In [276]:
#Find the inverses of the matrices B_ch6

B_ch6_inv = np.linalg.inv(B_ch6)
print('The inverses of the matrices B_ch6: ', B_ch6_inv)

The inverses of the matrices B_ch6:  [[ 0.5        -0.66666667]
 [-0.5         1.        ]]


In [277]:
#Verification

print ('B_ch6*B_ch6_inv=I is ', np.allclose(B_ch6.dot(B_ch6_inv), I))


B_ch6*B_ch6_inv=I is  True


**Quiz p.19, Question 3**

In [292]:
#Which matrix is the inverse of matrix A

A=np.array([[2,2], [1,2]])


# Answer options
A_a=np.array([[2,-2], [-1,2]])
A_b=np.array([[-2,2], [1,-2]])
A_c=np.array([[2,2], [-1,-2]])
A_d=np.array([[-2,-2], [1,2]])


Answer_a=0.5*A_a
Answer_b=0.5*A_b
Answer_c=0.5*A_c
Answer_d=0.5*A_d



In [293]:
A_inv=np.linalg.inv(A)

print ('The inverses of the matrices A: ', A_inv)
print()
print('Answer options:')
print('a) ', Answer_a)
print()
print('b) ', Answer_a)
print()
print('c) ', Answer_a)
print()
print('d) ', Answer_a)

print()

print('Correct answer: ')
print('Answer_a:', '\n', np.allclose(A_inv, Answer_a))
print ()
print('Answer_b:', '\n', np.allclose(A_inv, Answer_b))
print ()
print('Answer_c:', '\n', np.allclose(A_inv, Answer_c))
print ()
print('Answer_d:', '\n', np.allclose(A_inv, Answer_d))

The inverses of the matrices A:  [[ 1.  -1. ]
 [-0.5  1. ]]

Answer options:
a)  [[ 1.  -1. ]
 [-0.5  1. ]]

b)  [[ 1.  -1. ]
 [-0.5  1. ]]

c)  [[ 1.  -1. ]
 [-0.5  1. ]]

d)  [[ 1.  -1. ]
 [-0.5  1. ]]

Correct answer: 
Answer_a: 
 True

Answer_b: 
 False

Answer_c: 
 False

Answer_d: 
 False


In [316]:
print ('Correct answer: ')

print('Answer_a:', '\n', np.allclose(A.dot(Answer_a), I))
print ()
print('Answer_b:', '\n', np.allclose(A.dot(Answer_b), I))
print ()
print('Answer_c:', '\n', np.allclose(A.dot(Answer_c), I))
print ()
print('Answer_d:', '\n', np.allclose(A.dot(Answer_d), I))

Correct answer: 
Answer_a: 
 True

Answer_b: 
 False

Answer_c: 
 False

Answer_d: 
 False


**Chap10. Question 1 a)**

In [311]:
Coefficient = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
Answer_ch10 = np.array([-7, 5, 2])

print('Coefficient', Coefficient)
print()
print('Answer',Answer_ch10)

Coefficient [[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]

Answer [-7  5  2]


In [301]:
# The answer to the system of equations.

x = np.linalg.solve(Coefficient, Answer_ch10)

print('x: ', x)

x:  [ 3.  4. -6.]


In [310]:
#Check

print ('Coefficient*x = ',Coefficient@x)
print()
print ('Coefficient*x=Answer: ', np.allclose(Coefficient@x, Answer_ch10))

Coefficient*x =  [-7.  5.  2.]

Coefficient*x=Answer:  True


**Chap10. Question 1 b)**

In [313]:
Coefficient = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
Answer_ch10 = np.array([1, -1, 1])

print('Coefficient', Coefficient)
print()
print('Answer',Answer_ch10)

Coefficient [[ 1 -2  3]
 [-1  3 -1]
 [ 2 -5  5]]

Answer [ 1 -1  1]


In [314]:
# The answer to the system of equations.

x = np.linalg.solve(Coefficient, Answer_ch10)

print('x: ', x)

x:  [ 8.  2. -1.]


In [315]:
#Check

print ('Coefficient*x = ',Coefficient@x)
print()
print ('Coefficient*x=Answer: ', np.allclose(Coefficient@x, Answer_ch10))

Coefficient*x =  [ 1. -1.  1.]

Coefficient*x=Answer:  True


**Chap 12. Question 1**

In [334]:
A=np.array([[3,-7,-2], [-3,5,1], [6,-4,0]])

I=np.eye(3)

print('Matrix A ', A)

Matrix A  [[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]


In [331]:
A_inv=np.linalg.inv(A)

print ('A_inv: ', A_inv)
print()
print ('A_inv is the inverses of the matrices A: ', np.allclose(A@A_inv, I))


A_inv:  [[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]

A_inv is the inverses of the matrices A:  True
None


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [326]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [337]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [338]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
